// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9CwY8uFsCVNsMfiEI7MnQWgiBNvEMIrE',
    appId: '1:423451554857:web:4c184c2e0fbac8267ed838',
    messagingSenderId: '423451554857',
    projectId: 'chat-app-c8751',
    authDomain: 'chat-app-c8751.firebaseapp.com',
    storageBucket: 'chat-app-c8751.firebasestorage.app',
    measurementId: 'G-XSWMZ9W5M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBatfCyMEJU4Y9YtuWXJAxftl2XRs7ERzk',
    appId: '1:423451554857:android:29dd8450e6b293147ed838',
    messagingSenderId: '423451554857',
    projectId: 'chat-app-c8751',
    storageBucket: 'chat-app-c8751.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMxuYaYvKvUmZ_MT3IlgOwXWe0Jv8GMB0',
    appId: '1:423451554857:ios:035a0be7e70df2567ed838',
    messagingSenderId: '423451554857',
    projectId: 'chat-app-c8751',
    storageBucket: 'chat-app-c8751.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMxuYaYvKvUmZ_MT3IlgOwXWe0Jv8GMB0',
    appId: '1:423451554857:ios:035a0be7e70df2567ed838',
    messagingSenderId: '423451554857',
    projectId: 'chat-app-c8751',
    storageBucket: 'chat-app-c8751.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9CwY8uFsCVNsMfiEI7MnQWgiBNvEMIrE',
    appId: '1:423451554857:web:25f1f0a95d3f12a97ed838',
    messagingSenderId: '423451554857',
    projectId: 'chat-app-c8751',
    authDomain: 'chat-app-c8751.firebaseapp.com',
    storageBucket: 'chat-app-c8751.firebasestorage.app',
    measurementId: 'G-P8WDYKYHJZ',
  );
}
